### ISSUE TITLE
rtt pkgs update 报 “-‘Configuration’ object has no attribute ‘BSP_ROOT’”

### ISSUE THREAD

**Issue by liuyangzys** [wugensheng-code/rtt_env#1]
操作系统: windows 10
python 版本:  3.10.7
使用 rtt menuconfig 、scons编译等都正常，但使用 rtt pkgs update 报 “-‘Configuration’ object has no attribute ‘BSP_ROOT’” 会报
``` -‘Configuration’ object has no attribute ‘BSP_ROOT’```

**Comment by wugensheng-code** [comment]
多谢反馈，我修一下。

**Comment by wugensheng-code** [comment]
已修复
